### ISSUE TITLE
Creacion de la tabla KEY, MAIL y OTROS

### ISSUE THREAD

**Issue by jeroalvarez1** [CodeSystem2022/X-FORCE_Ecommerce#9]
[PRODUCTO][MODELOS] Se requeire crear la tabla KEY, MAIL y OTROS correspondientes a la aplicación PRODUCTO

**Comment by CristianChosma** [comment]
[PRODUCTO][MODELOS] Según pedido, se  crearon las tablas KEY, MAIL y OTROS correspondientes a la aplicación PRODUCTO
